# Use an official Python runtime as a parent image
FROM python:3

# Set working directory in the container
WORKDIR /app

# Copy the Python script and requirements.txt into the container at /app
COPY requirements.txt /app/
COPY main.py /app/
COPY connections.py /app/
COPY service.py /app/
COPY tests.py /app/

# Install any needed dependencies specified in requirements.txt
# RUN pip install -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run your Python script when the container launches
CMD ["python", "main.py"]
